### ISSUE TITLE
Stops working on Omega protocol P5

### ISSUE THREAD

**Issue by Vspinax** [OverlayPlugin/cactbot#140]
### Description

Stops working on Omega protocol P5

### Additional Details / Steps to Reproduce

Timeline and alerts works perfectly fine, until I reach P5 in the omega protocol, then it just dissapears. No timeline, and no alerts. This has happened consistently over serveral game sessions. I have not edited the timeline, and I have english language on everything. before reaching P5 it works perfectly every time

### Cactbot Module

Raidboss (alerts & timelines)

### Configuration Info

```
Plugin Name          Enabled Version  Path
----------------------------------------------------------------------------------------------------------------------------------------
FFXIV_ACT_Plugin.dll True    2.7.0.1  C:\Program Files (x86)\Advanced Combat Tracker\FFXIV_ACT_Plugin.dll
OverlayPlugin.dll    True    0.19.29  C:\Users\Vegard\AppData\Roaming\Advanced Combat Tracker\Plugins\OverlayPlugin\OverlayPlugin.dll
CactbotOverlay.dll   True    0.31.4.0 C:\Users\Vegard\AppData\Roaming\Advanced Combat Tracker\Plugins\cactbot\cactbot\CactbotOverlay.dll
Triggernometry.dll   True    1.1.7.4  C:\Users\Vegard\AppData\Roaming\Advanced Combat Tracker\Plugins\Triggernometry.dll


Overlay Name URL
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Overlay      https://haeruhaeru.github.io/mopimopi/?HOST_PORT=ws://127.0.0.1/fake/
Timers       file:///C:/Users/Vegard/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.23.6/cactbot/ui/raidboss/raidboss.html?timeline=1&alerts=0
others test  https://zeffuro.github.io/ZeffUI/
Alerts       file:///C:/Users/Vegard/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/cactbot/ui/raidboss/raidboss.html?timeline=0&alerts=1


Various Settings                                Value
--------------------------------------------------------------------------------------------------------------------------------------------
Plugin Language                                 English
Machina Region                                  Global
Game Version                                    2024.03.27.0000.0000
Screen Mode                                     Borderless Windowed
ACT Process Elevation                           Elevated (Admin)
FFXIV Process Elevation                         Not Elevated
Inject and use Deucalion for network data       True
Hide Chat Log (for privacy)                     False
Use WinPCap-compatible library for network data False
Disable high-performance network filter         False
Disable Combine Pets with Owner                 False
Disable Damage Shield estimates                 False
(DEBUG) Enable Debug Options                    False
(DEBUG) Log all Network Packets                 False
(DEBUG) Also Show 'Real' DoT Ticks              False
(DEBUG) Simulate Individual DoT Crits           False
(DEBUG) Graph Potency, not Damage               False
(DEBUG) Enable Benchmark Tab                    False
Cactbot User Dir                                C:\Users\Vegard\AppData\Roaming\Advanced Combat Tracker\Plugins\cactbot-0.23.6\cactbot\user\
```

### Confirmation

- [X] I reviewed <a href='/OverlayPlugin/cactbot/blob/main/docs/FAQ-Troubleshooting.md'> Common Issues and Workarounds</a> and verified that my settings are correct.
- [X] I used the search function to confirm this issue doesn't already exist.

**Comment by valarnin** [comment]
Your `Alerts` overlay has the correct URL (`.../Plugins/cactbot/cactbot/ui/...`), but your `Timers` overlay does not (`.../Plugins/cactbot-0.23.6/cactbot/ui/...`).

In addition, your `Cactbot User Dir` is also pointing at the wrong folder and should be updated (and any associated custom user JS/CSS moved over).

As for why TOP itself might be desyncing, the only change to triggers was over 5 months ago, and the only change to timelines was an order adjustment for one of the branches in P5 which wouldn't impact syncing or triggers.

https://github.com/OverlayPlugin/cactbot/commit/8a680429b0d012b922528acf66f612b0f4153dfa#diff-c5150792ce5233e5e5fea58f1d109930ee748977e873a94461c37f44e212c20c

---

If fixing your overlay and user dir paths doesn't resolve the issue, can you upload a log file (split via https://overlayplugin.github.io/cactbot/util/logtools/splitter.html, feel free to use the anonymizer option on the splitter) and a dev can review?

**Comment by Vspinax** [comment]
That's a bit awkward. I haven't used it in a long time until recently, so I removed the plugin before reinstalling it, guess it wasn't as much of a clean install as I thought...
Anyways that solved the problem, thank you very much! 

Not sure if it was TOP specific, I don't use it elsewhere. I read somewhere something about changing the ID's of the P5 bosses, so my guess is that it could have had something to do with that?

**Comment by valarnin** [comment]
> That's a bit awkward. I haven't used it in a long time until recently, so I removed the plugin before reinstalling it, guess it wasn't as much of a clean install as I thought...

There was a change made a while ago to remove the version number from the path specifically to resolve this sort of issue in the future, but there's not a good way to handle changing to the correct path automatically because the update process that actually extracts to the folder is controlled by ACT itself, not cactbot.

You're not the first person to have this issue, most of those users get their problem resolved on the discord #troubleshooting channel.

> Not sure if it was TOP specific, I don't use it elsewhere. I read somewhere something about changing the ID's of the P5 bosses, so my guess is that it could have had something to do with that?

Referencing the older path can cause all sorts of strange issues, so I'm not sure exactly what was causing TOP P5 specifically to fail, but I'm glad that this resolved the problem for you.
