### ISSUE TITLE
Raidemulator parser language setting is incorrect for non-ACT parse language log files

### ISSUE THREAD

**Issue by Souma-Sumire** [OverlayPlugin/cactbot#149]
### Description

During playback encounters, RegexBuild constructs regular expressions using the language of the parsing plugin instead of the actual language used in the logs. This results in regex mismatches (affecting the popup-text area).

### Additional Details / Steps to Reproduce

_Translated from AI. Please point out any areas where I may not have explained clearly. Thank you for your understanding and assistance!_

## Reproduce
1. Set FFXIV ACT plugin language to English.
1. Open raidemulator.html in a browser (using WebSocket).
1. Load log files generated by the (not English) client.
1. Click the Play button.

At this point, the "column" area on the right is functioning normally. However, there is an issue with the real-time popup-text-container area on the left.

It has been observed that triggers necessitating regex matching based on sourceName are not being simulated accurately.

### Test
Set FFXIV ACT plugin language to Japanese, Load log files generated by the Chinese client.

Changes b09e31d, It's observed that during the first instantiation of PopupText, [source code](https://github.com/OverlayPlugin/cactbot/blob/7db29bae46aa4de95e17f8001bdcea252f449eb8/ui/raidboss/popup-text.ts#L901-L926) parserLang is set to the language of the ACT plugin, which is incorrect.

Here's debug output:
```
count:4,lang:cn
localNetRegex: /^20\|[^|]*\|[^|]*\|斯塔缇丝\|8CBC\|/i
 // ... Omit more ...
count:0,lang:ja
localNetRegex: /^00\|[^|]*\|(?:0039|0139|0239)\|[^|]*\|(?:レディチェックを開始しました|(?:[^\s:|]+(?: [^\s:|]+)?|)がレディチェックを開始しました).*?\|/i
```
### Fix
I attempted to address this issue with changes in version 58eab9d, and now it can correctly acquire the language for constructing regular expressions. 

```
count:4,lang:cn
localNetRegex: /^20\|[^|]*\|[^|]*\|斯塔缇丝\|8CBC\|/i
 // ... Omit more ...
count:0,lang:cn
localNetRegex: /^00\|[^|]*\|(?:0039|0139|0239)\|[^|]*\|(?:发起了准备确认|(?:[^\s:|]+(?: [^\s:|]+)?|)发起了准备确认).*?\|/i
```

But I'm unsure if this approach is standard. I would greatly appreciate any insights or guidance. Thank you very much.

Here is my [branch](https://github.com/Souma-Sumire/cactbot/tree/1), in case anyone needs it.

### Cactbot Module

Raid Emulator

### Configuration Info

```
Plugin Name          Enabled Version   Path
----------------------------------------------------------------------------------------------------------------------------------------
FFXIV_ACT_Plugin.dll True    2.7.0.2   C:\Users\55346\AppData\Roaming\Advanced Combat Tracker\Plugins\FFXIV_ACT_Plugin.dll
OverlayPlugin.dll    True    0.19.29   C:\Users\55346\AppData\Roaming\Advanced Combat Tracker\Plugins\OverlayPlugin\OverlayPlugin.dll
CactbotOverlay.dll   True    0.31.5.0  C:\Users\55346\AppData\Roaming\Advanced Combat Tracker\Plugins\cactbot\cactbot\CactbotOverlay.dll


Overlay Name URL
-----------------------------------------------------------------------------------------------------------------------------------
Omitted


Various Settings                                Value
-----------------------------------------------------------------------------------------------------------------------------------
Plugin Language                                 Japanese
Machina Region                                  Global
Game Version                                    (not running)
Screen Mode                                     (unknown)
ACT Process Elevation                           Elevated (Admin)
FFXIV Process Elevation                         (unknown)
Inject and use Deucalion for network data       True
Hide Chat Log (for privacy)                     False
Use WinPCap-compatible library for network data False
Disable high-performance network filter         False
Disable Combine Pets with Owner                 False
Disable Damage Shield estimates                 False
(DEBUG) Enable Debug Options                    False
(DEBUG) Log all Network Packets                 False
(DEBUG) Also Show 'Real' DoT Ticks              False
(DEBUG) Simulate Individual DoT Crits           False
(DEBUG) Graph Potency, not Damage               False
(DEBUG) Enable Benchmark Tab                    False
Cactbot User Dir                                C:\Users\55346\AppData\Roaming\Advanced Combat Tracker\Plugins\cactbot\cactbot\user
```

### Confirmation

- [X] I reviewed <a href='/OverlayPlugin/cactbot/blob/main/docs/FAQ-Troubleshooting.md'> Common Issues and Workarounds</a> and verified that my settings are correct.
- [X] I used the search function to confirm this issue doesn't already exist.

**Comment by valarnin** [comment]
I believe that the correct way to fix this without potentially breaking changes to downstream consumers is instead to modify raidemulator itself. Can you test that this works to resolve the issue, and if so feel free to PR it?

```diff
diff --git a/ui/raidboss/emulator/data/RaidEmulator.ts b/ui/raidboss/emulator/data/RaidEmulator.ts
index 87bcfec7a..960e36b46 100644
--- a/ui/raidboss/emulator/data/RaidEmulator.ts
+++ b/ui/raidboss/emulator/data/RaidEmulator.ts
@@ -35,8 +35,10 @@ export default class RaidEmulator extends EventBus {
   ): void {
     // If language was autodetected from the encounter, set the current ParserLanguage
     // appropriately
-    if (enc.language)
+    if (enc.language) {
       this.options.ParserLanguage = enc.language;
+      this.popupText?.setParserLanguage(enc.language);
+    }
 
     this.currentEncounter = new AnalyzedEncounter(this.options, enc, this, watchCombatantsOverride);
     void this.dispatch('preCurrentEncounterChanged', this.currentEncounter);
diff --git a/ui/raidboss/emulator/overrides/RaidEmulatorPopupText.ts b/ui/raidboss/emulator/overrides/RaidEmulatorPopupText.ts
index c960f7219..5679c88d6 100644
--- a/ui/raidboss/emulator/overrides/RaidEmulatorPopupText.ts
+++ b/ui/raidboss/emulator/overrides/RaidEmulatorPopupText.ts
@@ -1,3 +1,4 @@
+import { Lang } from '../../../../resources/languages';
 import { UnreachableCode } from '../../../../resources/not_reached';
 import { EventResponses, LogEvent } from '../../../../types/event';
 import { RaidbossFileData } from '../../../../types/trigger';
@@ -262,4 +263,8 @@ export default class RaidEmulatorPopupText extends StubbedPopupText {
       expires: endTimestamp,
     });
   }
+
+  setParserLanguage(lang: Lang): void {
+    this.parserLang = lang;
+  }
 }
```

(I think that eventually we're going to need to do a bigger sweep of changes to clean up a bunch of stuff, with potentially breaking changes like your original suggestion, but we should give downstream consumers and users ample notice and do all those potentially-breaking changes at once)

**Comment by Souma-Sumire** [comment]
> Can you test that this works to resolve the issue

Yes, I tested it, and it resolved the issue. Thank you for your help!
