### ISSUE TITLE
kr cactbot

### ISSUE THREAD

**Issue by kblue061** [OverlayPlugin/cactbot#152]
I'm sending you a file to send to you.
[cactbot.zip](https://github.com/OverlayPlugin/cactbot/files/15353986/cactbot.zip)

**Comment by wexxlee** [comment]
> I'm sending you a file to send to you. [cactbot.zip](https://github.com/OverlayPlugin/cactbot/files/15353986/cactbot.zip)

Thanks, but not sure what you're asking for.  If you're having an issue with cactbot, you may want to start by asking in the #troubleshooting channel on the [ACT Discord](https://discord.gg/ahFKcmx) (and to help speed the resolution, I'd recommend clearly explaining the issue you're having, and pasting the results of the "Copy Tech Support Into to Clipboard" button from the `OverlayPlugin.dll` tab in your ACT client.)  That's the fastest way to engage in a dialog to get your issue addressed.

If you're not able to get assistance there, please feel free to [open a support issue here -- and please complete the bug form](https://github.com/OverlayPlugin/cactbot/issues/new?assignees=&labels=bug%2Cneeds-review&projects=&template=01-bug_report.yml) so we can better assist you.  

Thanks.

**Comment by kblue061** [comment]
I am using the Korean server and using the 6.51 fix version. There seems to be a bug in the cactbot plugin's The Unending coil of Bahamut where the spread, stack, Dynamo, and Chariot are not displayed or read in the section where the boss is Nael in Phase 2: Nael Deus Darnus and Phase 3: Bahamut Prime. If you don't mind, can you fix it?

**Comment by valarnin** [comment]
cactbot's Nael quote triggers rely on the NpcYell log line from OverlayPlugin. Please make sure your opcodes are up to date, via:

1. Make sure that the opcode autoupdater is not throwing an error in the log panel in OverlayPlugin
2. Manually verify the opcodes are up to date in `%APPDATA%\Advanced Combat Tracker\Config\RainbowMage.OverlayPlugin.config.json`, there should be a section that matches the following:
```json
    "Korean": {
      "2024.04.18.0000.0000": {
        "MapEffect": {
          "opcode": 753,
          "size": 11
        },
        "CEDirector": {
          "opcode": 424,
          "size": 16
        },
        "RSVData": {
          "opcode": 814,
          "size": 1080
        },
        "NpcYell": {
          "opcode": 674,
          "size": 32
        },
        "BattleTalk2": {
          "opcode": 642,
          "size": 40
        },
        "Countdown": {
          "opcode": 190,
          "size": 48
        },
        "CountdownCancel": {
          "opcode": 950,
          "size": 40
        },
        "ActorMove": {
          "opcode": 483,
          "size": 16
        },
        "ActorSetPos": {
          "opcode": 765,
          "size": 24
        }
      }
    }
```

If the opcodes are up to date, you will need to provide a log file for us to debug further. You can do so by opening the [log splitter](https://overlayplugin.github.io/cactbot/util/logtools/splitter.html), dragging a log file with a pull that goes to Nael on to the page, optionally enabling the anonymize option, selecting a Nael pull, and then exporting it. Then you can upload the log file to this issue.
