### ISSUE TITLE
Cactbot is not loading - logs uploaded

### ISSUE THREAD

**Issue by fujikawa57** [OverlayPlugin/cactbot#160]
Here is a copy of the logs

> [6/2/2024 8:30:01 PM] Info: AssemblyResolver: Loaded: HtmlRenderer, Version=0.19.29.0, Culture=neutral, PublicKeyToken=null
> [6/2/2024 8:30:01 PM] Info: AssemblyResolver: Loaded: CefSharp, Version=95.7.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
> [6/2/2024 8:30:01 PM] Info: InitPlugin: PluginDirectory = C:\Users\XXXX\AppData\Roaming\Advanced Combat Tracker\Plugins\OverlayPlugin
> [6/2/2024 8:30:01 PM] Info: AssemblyResolver: Loaded: CefSharp.OffScreen, Version=95.7.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
> [6/2/2024 8:30:01 PM] Info: AssemblyResolver: Loaded: CefSharp.Core, Version=95.7.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
> [6/2/2024 8:30:01 PM] Info: AssemblyResolver: Loaded: CefSharp.Core.Runtime, Version=95.7.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
> [6/2/2024 8:30:01 PM] Info: AssemblyResolver: Loaded: System.Resources.Extensions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
> [6/2/2024 8:30:01 PM] Info: AssemblyResolver: Loaded: System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
> [6/2/2024 8:30:01 PM] Info: AssemblyResolver: Loaded: System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> [6/2/2024 8:30:01 PM] Info: AssemblyResolver: Loaded: System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> [6/2/2024 8:30:01 PM] Info: AssemblyResolver: Loaded: Fleck, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null
> [6/2/2024 8:30:01 PM] Info: InitPlugin: Initialised.
> [6/2/2024 8:30:02 PM] Error: Got a subscription for missing event "onUserFileChanged"!
> [6/2/2024 8:30:02 PM] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
>    at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
>    at RainbowMage.OverlayPlugin.EventDispatcher.ProcessHandlerMessage(IEventReceiver receiver, String data)
> [6/2/2024 8:30:02 PM] Error: Got a subscription for missing event "onForceReload"!
> [6/2/2024 8:30:02 PM] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadData"!
>    at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
>    at RainbowMage.OverlayPlugin.EventDispatcher.ProcessHandlerMessage(IEventReceiver receiver, String data)
> [6/2/2024 8:30:02 PM] Info: Cactbot: BrowserConsole: Uncaught (in promise) TypeError: Cannot read properties of null (reading 'detail') (Source: file:///C:/Users/XXXX/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/cactbot/ui/raidboss/raidboss.bundle.js, Line: 4808)
> [6/2/2024 8:30:03 PM] Info: Found in combat memory via InCombatMemory61.
> [6/2/2024 8:30:04 PM] Info: Found combatant memory via CombatantMemory65.
> [6/2/2024 8:30:04 PM] Info: Found content finder settings memory via ContentFinderSettingsMemory651.
> [6/2/2024 8:30:04 PM] Info: Found party memory via PartyMemory65.
> [6/2/2024 8:30:05 PM] Info: Found job Gauge memory via JobGaugeMemory655.
> [6/2/2024 8:30:05 PM] Info: Found target memory via TargetMemory63.
> [6/2/2024 8:30:05 PM] Info: Found enmity memory via EnmityMemory60.
> [6/2/2024 8:30:06 PM] Info: Found aggro memory via AggroMemory60.
> [6/2/2024 8:30:06 PM] Info: Found enmity HUD memory via EnmityHudMemory62.
> [6/2/2024 8:30:06 PM] Info: AssemblyResolver: Loaded: YamlDotNet, Version=12.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e

This is the code in Line 4808 of the raidboss.bundle.js 
```
const loadUser = async e => {
      // The basePath isn't using for anything other than cosmetic printing of full paths,
      // so replace any slashes here for uniformity.  In case anybody is using cactbot on
      // Linux (?!?), support any style of slashes elsewhere.
      const basePath = `${e.detail.userLocation.replace(/[/\\]*$/, '')}\\`;
      const localFiles = e.detail.localUserFiles;
      options.SystemInfo = {
        cactbotVersion: e.detail.cactbotVersion,
        overlayPluginVersion: e.detail.overlayPluginVersion,
        ffxivPluginVersion: e.detail.ffxivPluginVersion,
        actVersion: e.detail.actVersion,
        gameRegion: e.detail.gameRegion
      };
```

**Comment by valarnin** [comment]
You do not have the cactbot ACT plugin loaded or enabled.

1. Go to `Plugins` > `Plugin Listing`
2. If there is a `CactbotOverlay.dll` plugin listed, enable it. Otherwise, use the `Get Plugins...` button in the top right to get the cactbot plugin
3. Ensure that the first plugin on the tab is `FFXIV_ACT_Plugin.dll`, then any amount of other plugins, then `OverlayPlugin.dll`, then any amount of other plugins, then `CactbotOverlay.dll`
4. After ensuring that the required plugins are present and enabled, restart ACT.

![image](https://github.com/OverlayPlugin/cactbot/assets/6119598/2538ede5-42ba-4692-9ea2-4b1ff042ffdd)

**Comment by fujikawa57** [comment]
> You do not have the cactbot ACT plugin loaded or enabled.
> 
> 1. Go to `Plugins` > `Plugin Listing`
> 2. If there is a `CactbotOverlay.dll` plugin listed, enable it. Otherwise, use the `Get Plugins...` button in the top right to get the cactbot plugin
> 3. Ensure that the first plugin on the tab is `FFXIV_ACT_Plugin.dll`, then any amount of other plugins, then `OverlayPlugin.dll`, then any amount of other plugins, then `CactbotOverlay.dll`
> 4. After ensuring that the required plugins are present and enabled, restart ACT.
> 
> ![image](https://private-user-images.githubusercontent.com/6119598/335882147-2538ede5-42ba-4692-9ea2-4b1ff042ffdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNDU5NDUsIm5iZiI6MTcxNzM0NTY0NSwicGF0aCI6Ii82MTE5NTk4LzMzNTg4MjE0Ny0yNTM4ZWRlNS00MmJhLTQ2OTItOWVhMi00YjFmZjA0MmZmZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDJUMTYyNzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWI1ZTk2YmZmMDNlYWNhYmQ4YjI2MjU3NzlmNjY3MWYzZDRkNTg5YjhlOTE3ZTg0MzhiYTVhYTZiZTc4MGJhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-JfoUYP6p_vWVgsQwnAtWBX0ksFbBn-LUsnMO94zWb4)

Hi, I did this. Apparently, I missed enabling the plugin. Anyway, it still didn't show when trying out in Summerford's striking dummy. Did I miss any other settings?

**Comment by valarnin** [comment]
Make sure the game is running, then:

Go to `Plugins` > `OverlayPlugin.dll` > `General`, click the `Copy Tech Support Info to Clipboard` button, and paste here. Feel free to edit out your username from paths.

**Comment by fujikawa57** [comment]
```
Plugin Name          Enabled Version  Path
---------------------------------------------------------------------------------------------------------------------------------------
FFXIV_ACT_Plugin.dll True    2.7.0.2  C:\Users\XXXX\AppData\Roaming\Advanced Combat Tracker\Plugins\FFXIV_ACT_Plugin.dll
OverlayPlugin.dll    True    0.19.29  C:\Users\XXXX\AppData\Roaming\Advanced Combat Tracker\Plugins\OverlayPlugin\OverlayPlugin.dll
CactbotOverlay.dll   True    0.31.5.0 C:\Users\XXXX\AppData\Roaming\Advanced Combat Tracker\Plugins\cactbot\cactbot\CactbotOverlay.dll


Overlay Name URL
---------------------------------------------------------------------------------------------------------------------------------
Parse        https://hibiyasleep.github.io/kagerou/overlay/
Cactbot      file:///C:/Users/XXXX/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/cactbot/ui/raidboss/raidboss.html


Various Settings                                Value
------------------------------------------------------------------------------------------------------------------------------------
Plugin Language                                 English
Machina Region                                  Global
Game Version                                    2024.04.23.0000.0000
Screen Mode                                     Borderless Windowed
ACT Process Elevation                           Not Elevated
FFXIV Process Elevation                         Not Elevated
Inject and use Deucalion for network data       True
Hide Chat Log (for privacy)                     False
Use WinPCap-compatible library for network data False
Disable high-performance network filter         False
Disable Combine Pets with Owner                 False
Disable Damage Shield estimates                 False
(DEBUG) Enable Debug Options                    False
(DEBUG) Log all Network Packets                 False
(DEBUG) Also Show 'Real' DoT Ticks              False
(DEBUG) Simulate Individual DoT Crits           False
(DEBUG) Graph Potency, not Damage               False
(DEBUG) Enable Benchmark Tab                    False
Cactbot User Dir                                C:\Users\XXXX\AppData\Roaming\Advanced Combat Tracker\Plugins\cactbot\cactbot\user\
```

**Comment by valarnin** [comment]
All of your tech support info looks good now. The only other thing I can think of is that you have something interfering with the in-game chat, e.g. an XIVLauncher/Dalamud plugin, or you don't have the correct chat lines enabled for the summerford farm test to work (`/bow` to the dummy and have that text show in the chat box, or countdown and have the `Engage!` text show in the chat box, or `/e testNetRegexTimeline` and have that text show in the chat box).

**Comment by fujikawa57** [comment]
Hi! Sorry for the late reply. I just tried with the emote logs enabled and it worked. Thank you!

**Comment by valarnin** [comment]
I think you're saying that your issues are resolved now? Or are you still having issues with cactbot working in instanced content?

**Comment by fujikawa57** [comment]
It's now working in Summerford Farms. However, it's still not working on instanced content. Currently doing an alliance raid in DF and the timeline and notifs are not showing.

**Comment by wexxlee** [comment]
> It's now working in Summerford Farms. However, it's still not working on instanced content. Currently doing an alliance raid in DF and the timeline and notifs are not showing.

You may want to check the coverage report [here](https://overlayplugin.github.io/cactbot/util/coverage/coverage.html).  TLDR: There are no timelines or triggers for Labryinth, Syrcus, or Void Ark; there is limited support generally for older content.

**Comment by fujikawa57** [comment]
Oh! Thanks for this. I guess it's working already. I tried it out at Thaleia and the triggers showed. Thank you! This is solved aready. :)

**Comment by xiashtra** [comment]
Closing as solved per user feedback.
