### ISSUE TITLE
docs: Update Log Guide to match `264 LineAbilityExtra` changes

### ISSUE THREAD

**Issue by xiashtra** [OverlayPlugin/cactbot#179]
### Description

Log Guide does not match actual line format

### Additional Details / Steps to Reproduce

`264 LineAbilityExtra` was updated in OverlayPlugin/OverlayPlugin#353 to add a new field for animation lock time.  The updated line format needs to be added to the Log Guide documentation.

### Cactbot Module

Other

### Configuration Info

n/a

### Confirmation

- [X] I reviewed <a href='/OverlayPlugin/cactbot/blob/main/docs/FAQ-Troubleshooting.md'> Common Issues and Workarounds</a> and verified that my settings are correct.
- [X] I used the search function to confirm this issue doesn't already exist.

**Comment by xiashtra** [comment]
@xpdota

**Comment by xpdota** [comment]
@xiashtra Did you want me to do this or are you taking care of it?

**Comment by xiashtra** [comment]
> @xiashtra Did you want me to do this or are you taking care of it?

It'd be better if you did it since you have the example lines already and know what the format is supposed to be.

Eventually, it would be nice to move the Log Guide over to the OverlayPlugin side and enforce updates when a line changes automatically.
