### ISSUE TITLE
How can i find the mapping of npcNameId

### ISSUE THREAD

**Issue by ElinLiu0** [OverlayPlugin/cactbot#189]
### What's your question?

Hi,i'm a developer from @NewMoe-Technology team,currently we try to build a custom tts system and we need to prerendering the audio.

Here i found some `${name}` placeholder were comes with some `npcNameId`,although i saw that there's comment in the code that shows what's that npc name in english,but i haven't found that there's some file shows the ja name and cn name.

I'm not a js or ts expert,my mainly programming language is Python.So is there any help that can tell me where can i such kind of map?

**Comment by valarnin** [comment]
You can use XIVAPI:
```
https://beta.xivapi.com/api/1/sheet/BNpcName/<decimal ID>?fields=Singular@en,Singular@de,Singular@fr,Singular@ja
```
Where `<decimal ID>` is the decimal/base 10 ID of the name. For example `BNpcNameID` of `303D` base-16 hex would be an ID of `12349` decimal, resulting in this request:
```
https://beta.xivapi.com/api/1/sheet/BNpcName/12349?fields=Singular@en,Singular@de,Singular@fr,Singular@ja
```

Which gives this JSON response:
```json
{
  "schema": "exdschema@9e9ccb05811e3e0dfc02662a33c288453f8502ab-2024.04.23.0000.0000",
  "row_id": 12349,
  "fields": {
    "Singular": "Haam Forlorn",
    "Singular@de": "Haam-Verloren[a]",
    "Singular@fr": "délaissé de Haam",
    "Singular@ja": "ハーム・フォーローン"
  }
}
```

More information is available here: https://beta.xivapi.com/api/1/docs

There's a non-"beta" version of XIVAPI which has 7.0 Dawntrail information, but that version will eventually be going away so it would be better to code against the beta version if possible.

**Comment by ElinLiu0** [comment]
> You can use XIVAPI:
> 
> ```
> https://beta.xivapi.com/api/1/sheet/BNpcName/<decimal ID>?fields=Singular@en,Singular@de,Singular@fr,Singular@ja
> ```
> 
> Where `<decimal ID>` is the decimal/base 10 ID of the name. For example `BNpcNameID` of `303D` base-16 hex would be an ID of `12349` decimal, resulting in this request:
> 
> ```
> https://beta.xivapi.com/api/1/sheet/BNpcName/12349?fields=Singular@en,Singular@de,Singular@fr,Singular@ja
> ```
> 
> Which gives this JSON response:
> 
> ```json
> {
>   "schema": "exdschema@9e9ccb05811e3e0dfc02662a33c288453f8502ab-2024.04.23.0000.0000",
>   "row_id": 12349,
>   "fields": {
>     "Singular": "Haam Forlorn",
>     "Singular@de": "Haam-Verloren[a]",
>     "Singular@fr": "délaissé de Haam",
>     "Singular@ja": "ハーム・フォーローン"
>   }
> }
> ```
> 
> More information is available here: https://beta.xivapi.com/api/1/docs
> 
> There's a non-"beta" version of XIVAPI which has 7.0 Dawntrail information, but that version will eventually be going away so it would be better to code against the beta version if possible.

May be i should try this weekend and i will bring my reply to you,thanks alot mate :)

**Comment by ElinLiu0** [comment]
> You can use XIVAPI:
> ```
> https://beta.xivapi.com/api/1/sheet/BNpcName/<decimal ID>?fields=Singular@en,Singular@de,Singular@fr,Singular@ja
> ```
> Where `<decimal ID>` is the decimal/base 10 ID of the name. For example `BNpcNameID` of `303D` base-16 hex would be an ID of `12349` decimal, resulting in this request:
> ```
> https://beta.xivapi.com/api/1/sheet/BNpcName/12349?fields=Singular@en,Singular@de,Singular@fr,Singular@ja
> ```
> 
> Which gives this JSON response:
> ```json
> {
>   "schema": "exdschema@9e9ccb05811e3e0dfc02662a33c288453f8502ab-2024.04.23.0000.0000",
>   "row_id": 12349,
>   "fields": {
>     "Singular": "Haam Forlorn",
>     "Singular@de": "Haam-Verloren[a]",
>     "Singular@fr": "délaissé de Haam",
>     "Singular@ja": "ハーム・フォーローン"
>   }
> }
> ```
> 
> More information is available here: https://beta.xivapi.com/api/1/docs
> 
> There's a non-"beta" version of XIVAPI which has 7.0 Dawntrail information, but that version will eventually be going away so it would be better to code against the beta version if possible.

Hi,reply here.
First,thanks for your guide and i can now get the information,great.
Second,ohoh,it's sounds like a bad news.According to our leader and other core dev:there is a lot of player using a custom triggers called TriggerNometry(Is that?).That means the trigger word from player may not same as cacbot preset and hard to predict.So i need find a more faster AI Audio rendering solution.

Finally,thanks your help.

BR
