### ISSUE TITLE
Cactbot Jobs: DOT no longer alerts before expiring

### ISSUE THREAD

**Issue by SeyEve** [OverlayPlugin/cactbot#191]
DOT spells particularly tested using biolysis no longer plays an alert sound before expiring, but if you set the option to alert when expired it does alert after the DOT falls off.

**Comment by fapolo** [comment]
Can confirm that. Tested with:
- Dia
- Byolosis
- Combust III
- Eukrasian Dosis III
- Stormbite
- Caustic Bite

For those, sounds don't play when using option "When counter is close to 0."

**Comment by Echoring** [comment]
I recently see a same case. 
In that case, ACT opened after login and without changing jobs/maps, so unable to access spellspeed.
Try change jobs and test again.
