### ISSUE TITLE
Jobs overlay not working

### ISSUE THREAD

**Issue by ItsJoeDove** [OverlayPlugin/cactbot#218]
### Description

Little buffs showing up and then nothing at all

### Additional Details / Steps to Reproduce

Once I start playing, the jobs overlay is the only one that isn't working. I restart the overlay and then it will show minimal buffs and when they are about to become off cooldown and when they are on cooldown (as intended). After a short while of playing nothing works from jobs overlay and I have to refresh it. Refreshing doesn't even work sometimes.

### Cactbot Module

Jobs

### Configuration Info

```
Plugin Name - Status - Version - Path
FFXIV_ACT_Plugin.dll - Enabled - 2.7.0.9 - <ACT Folder>\Plugins\FFXIV_ACT_Plugin.dll
OverlayPlugin.dll - Enabled - 0.19.32 - <ACT Folder>\Plugins\OverlayPlugin\OverlayPlugin.dll
CactbotOverlay.dll - Enabled - 0.32.1.0 - <ACT Folder>\Plugins\cactbot\cactbot\CactbotOverlay.dll

Overlay Name - URL
Ember - https://goldenchrysus.github.io/ffxiv/ember-overlay/
Cactbot - https://hibiyasleep.github.io/kagerou/overlay/
CACTBOTALERTS - file:///<ACT Folder>/Plugins/cactbot/cactbot/ui/raidboss/raidboss.html
DD Target Info - https://iamlokken.github.io/DeepDungeonOverlay/overlay/targetinfo/
DD Overlay - https://iamlokken.github.io/DeepDungeonOverlay/overlay/
OOPS! - file:///<ACT Folder>/Plugins/cactbot/cactbot/ui/oopsyraidsy/oopsyraidsy.html
JOBS - file:///<ACT Folder>/Plugins/cactbot/cactbot/ui/jobs/jobs.html
HUNTS - file:///<ACT Folder>/Plugins/cactbot/cactbot/ui/radar/radar.html

Various Settings - Value
Plugin Language - English
Machina Region - Global
Game Version - 2024.07.06.0000.0000
Screen Mode - Borderless Windowed
ACT Process Elevation - Elevated (Admin)
FFXIV Process Elevation - Not Elevated
Inject and use Deucalion for network data - True
Hide Chat Log (for privacy) - False
Use WinPCap-compatible library for network data - False
Disable high-performance network filter - False
Disable Combine Pets with Owner - False
Disable Damage Shield estimates - False
(DEBUG) Enable Debug Options - False
Cactbot User Dir - <ACT Folder>\Plugins\cactbot\cactbot\user\
```

### Confirmation

- [X] I reviewed <a href='/OverlayPlugin/cactbot/blob/main/docs/FAQ-Troubleshooting.md'> Common Issues and Workarounds</a> and verified that my settings are correct.
- [X] I used the search function to confirm this issue doesn't already exist.

**Comment by wexxlee** [comment]
> Once I start playing, the jobs overlay is the only one that isn't working. I restart the overlay and then it will show minimal buffs and when they are about to become off cooldown and when they are on cooldown (as intended). After a short while of playing nothing works from jobs overlay and I have to refresh it. Refreshing doesn't even work sometimes.

Hi there.  The `jobs` module is continuing to be updated to support Dawntrail, and more work is still in flight.  But tonight's release (0.32.2) included a number of fixes.  Could you recheck and see if this issue is fixed for you now? If not, could you update your issue with the jobs you're playing where you're still seeing an issue?  Thanks!

**Comment by ItsJoeDove** [comment]
Hi sorry for the late reply. I work a lot. I was able to run a couple dungeons today and I didn't notice it drop at all. I will be able to give better feedback tomorrow and the following days if it doesn't work. 

So far the only thing I notice was the cheese icon appearing while I still have food up.

**Comment by ItsJoeDove** [comment]
Jobs plug in is working great for me now thank you! @wexxlee

**Comment by wexxlee** [comment]
> Jobs plug in is working great for me now thank you! @wexxlee

Glad to hear it!  I think the thanks should go to @MaikoTan and @Echoring though. =)

**Comment by ItsJoeDove** [comment]
Thank you very much @MaikoTan and @Echoring ! I love Cactobot and the plugins!
