### ISSUE TITLE
Changing audio output

### ISSUE THREAD

**Issue by Anathema30** [OverlayPlugin/cactbot#237]
### What's your question?

Hi.
I've been trying to change the audio output for cactbot stuff as it constantly broadcast through my microphone input and since there's 0 option anywhere to change that, i'm asking if there's a special method.
I tried SlimDX and Win10 sound option and neither work. 
I use Virtual Audio cable to create audio lines as i'm using a TTS program but cactbot send audio directly through it.

**Comment by valarnin** [comment]
All audio for cactbot should use your default audio output device, i.e. what you have selected in the Windows Sound control panel:

![image](https://github.com/user-attachments/assets/6bacb603-c6aa-4dc1-8abe-d7733f2f98d9)

For clarification, there are two types of audio for cactbot.

1. Sound-based alerts and sound files, e.g. the ready check `Game On` audio
  a. Plays through CEF, should show up as `CefSharp.BrowserSubprocess` in the Windows volume mixer:
![image](https://github.com/user-attachments/assets/cd64b8ab-716e-48c7-8b17-105d24f1b4d7)
2. TTS, if you have it enabled
  a. Plays through the ACT process.

There is no in-application location to change the output audio device. I'm not sure if there's a Windows-level way to change the default audio output device per process.

You could technically write an ACT plugin to override the TTS method and redirect that audio to a specific audio device, but that would not change the audio output device of cactbot's sound-based alerts and sound files.

**Comment by Anathema30** [comment]
Ok thanks for the info.
Manage to sort it out, kinda-ish, now that i know the sound is from CefSHarp it make it a tad easier to isolate and sort it out just through my virtual cable. Writing a plugin would be a bit of a stretch for me.

**Comment by wexxlee** [comment]
@Anathema30 Sounds like you've got this resolved, so I'll close out the issue.  But feel free to re-open if you're still having any problems!
