### ISSUE TITLE
tank → Taunts, avoidance, and one-on-one duels notifications do not work.

### ISSUE THREAD

**Issue by shs1300** [OverlayPlugin/cactbot#323]
tank → Taunts, avoidance, and one-on-one duels notifications do not work.

**Comment by wexxlee** [comment]
Highly likely this is related to #328, so will close this for now pending a fix to #328 (as these features do seem to work fine in current int'l versions).  Please do re-open though if the eventual fix for the other PR doesn't address these issues.
