### ISSUE TITLE
M4S Sunrise Sabbath Lasers

### ISSUE THREAD

**Issue by QueueMander** [OverlayPlugin/cactbot#361]
### Description

Wrong Callout as to where to point the cannons.

### Additional Details / Steps to Reproduce

The color of cannon you should go to was correct but it says to point it towards E/W when the Winged Clones are facing E/W. Should've point point N/S.

### Cactbot Module

Raidboss (alerts & timelines)

### Configuration Info

```
Plugin Name - Status - Version - Path
FFXIV_ACT_Plugin.dll - Enabled - 2.7.1.8 - <ACT Folder>\Plugins\FFXIV_ACT_Plugin.dll
OverlayPlugin.dll - Enabled - 0.19.35 - <ACT Folder>\Plugins\OverlayPlugin\OverlayPlugin.dll
CactbotOverlay.dll - Enabled - 0.32.6.0 - <ACT Folder>\Plugins\cactbot\cactbot\CactbotOverlay.dll

Overlay Name - URL
Kagerou - https://hibiyasleep.github.io/kagerou/overlay/
Cact Alerts - file:///<ACT Folder>/Plugins/cactbot/cactbot/ui/raidboss/raidboss.html?timeline=0&alerts=1

Various Settings - Value
Plugin Language - English
Machina Region - Global
Game Version - 2024.08.02.0000.0000
Screen Mode - Borderless Windowed
ACT Process Elevation - Elevated (Admin)
FFXIV Process Elevation - Not Elevated
Inject and use Deucalion for network data - True
Hide Chat Log (for privacy) - False
Use WinPCap-compatible library for network data - False
Disable high-performance network filter - False
Disable Combine Pets with Owner - False
Disable Damage Shield estimates - False
(DEBUG) Enable Debug Options - False
Cactbot User Dir - <ACT Folder>\Plugins\cactbot\cactbot\user\
```

### Log & Screenshots

![wrong cactbot callout](https://github.com/user-attachments/assets/67f566c3-0dd2-4d0a-905e-b83965676a88)

### Confirmation

- [X] I reviewed <a href='/OverlayPlugin/cactbot/blob/main/docs/FAQ-Troubleshooting.md'> Common Issues and Workarounds</a> and verified that my settings are correct.
- [X] I used the search function to confirm this issue doesn't already exist.

**Comment by valarnin** [comment]
It's tower position detection. I can confirm and have video + log file if it's needed to debug.

I have a log+video where it detected first towers n/s but they were e/w.
Second towers were detected properly.

**Comment by wexxlee** [comment]
> It's tower position detection. I can confirm and have video + log file if it's needed to debug.
> 
> I have a log+video where it detected first towers n/s but they were e/w. Second towers were detected properly.

@valarnin Would you mind DMing me log & vod when you have a chance?  I only have a couple pulls with sunrise from the last few weeks (and most of my prog vod has been archived or cleared for space), and I'm not able to repro with what I have so would be super-helpful.  Thx!
