### ISSUE TITLE
No calls/alerts in M4S 

### ISSUE THREAD

**Issue by Sanayko** [OverlayPlugin/cactbot#368]
### Description

Cactbot doesn't make any calls in M4S, even tho it perfectly calls in M1S-M3S

### Additional Details / Steps to Reproduce

Hello!

Yesterday I had to make the experience that the cactbot calls aren't working in M4S for me.
I did the reclears in M1S-M3S before and they worked perfecty fine.
When I entered M4S I had to recognize that I don't get any calls except the alert "R4S Electrical Condenser Debuff Inital".
(green alert on screen). Didn't come any further in fight.

XIV Launcher is set in German
ACT Parse Language is set in German
Display language is set in English (en)

Friends who have everything set in english don't have these issues.

### Cactbot Module

Raidboss (alerts & timelines)

### Configuration Info

```
Plugin Name - Status - Version - Path
FFXIV_ACT_Plugin.dll - Enabled - 2.7.1.8 - <ACT Folder>\Plugins\FFXIV_ACT_Plugin.dll
OverlayPlugin.dll - Enabled - 0.19.35 - <ACT Folder>\Plugins\OverlayPlugin\OverlayPlugin.dll
CactbotOverlay.dll - Enabled - 0.32.6.0 - <ACT Folder>\Plugins\cactbot\cactbot\CactbotOverlay.dll

Overlay Name - URL
Alerts - file:///<ACT Folder>/Plugins/cactbot/cactbot/ui/raidboss/raidboss.html?timeline=0&alerts=1
Timeline - file:///<ACT Folder>/Plugins/cactbot/cactbot/ui/raidboss/raidboss.html?timeline=1&alerts=0
Meter - https://hibiyasleep.github.io/kagerou/overlay/

Various Settings - Value
Plugin Language - German
Machina Region - Global
Game Version - 2024.08.02.0000.0000
Screen Mode - Borderless Windowed
ACT Process Elevation - Elevated (Admin)
FFXIV Process Elevation - Elevated (Admin)
Inject and use Deucalion for network data - False
Hide Chat Log (for privacy) - False
Use WinPCap-compatible library for network data - False
Disable high-performance network filter - False
Disable Combine Pets with Owner - False
Disable Damage Shield estimates - False
(DEBUG) Enable Debug Options - False
Cactbot User Dir - <ACT Folder>\Plugins\cactbot\cactbot\user\
```

### Log & Screenshots

[M4S Savage LOG.log](https://github.com/user-attachments/files/16733291/M4S.Savage.LOG.log)

### Confirmation

- [X] I reviewed <a href='/OverlayPlugin/cactbot/blob/main/docs/FAQ-Troubleshooting.md'> Common Issues and Workarounds</a> and verified that my settings are correct.
- [X] I used the search function to confirm this issue doesn't already exist.

**Comment by wexxlee** [comment]
This is happening because we haven't version-bumped since #334 was merged.  It will be working correctly in the next release.

**Comment by mooondark** [comment]
If the translation does not existe, callouts are displayed in English, no?

It was like this before, I don't think it has changed.

**Comment by wexxlee** [comment]
> If the translation does not exist, callouts are displayed in English, no?
> 
> It was like this before, I don't think it has changed.

True, but if the ACT parsing language is non-en, cactbot will use what it has from replaceSync to localize the trigger regex -- so if the boss's name (commonly used in a lot of netRegex) is different in that language and there is no replaceSync block for the user's parsing language, the netRegex will not match.

**Comment by mooondark** [comment]
> True, but if the ACT parsing language is non-en, cactbot will use what it has from replaceSync to localize the trigger regex -- so if the boss's name (commonly used in a lot of netRegex) is different in that language and there is no replaceSync block for the user's parsing language, the netRegex will not match.

Oh ok, thanks for this clarification 👍
