### ISSUE TITLE
raidboss: customize general outputs

### ISSUE THREAD

**Issue by Echoring** [OverlayPlugin/cactbot#390]
### Feature(s) Requested

General output from `resource/output.ts` are widely used in raidboss alert text. Although it is possible to directly modify every trigger output text, it can be annoying when you have trouble reading a widely used general output.
For example, I have some trouble to quickly respond to NW/SW/NE/SE style direction abbr. I have to check all triggers that include these direction and edit them. 
Is it possible to add a tab in cactbot config panel to allow user custom general outputs? I believe this will also benefit left/west, right/east preference issue.

**Comment by wexxlee** [comment]
I'm wondering if this might be something that would make more sense to support in user config files but not actually through the config UI?

I think the challenge with the UI is that we don't really expose when a trigger is using something from `Outputs` - we only display the actual value and let the user edit it.  So a user could go in and try to override `Outputs` values in the config UI without necessarily understanding how that change will propagate and where it will be used.  (I'm just envisioning issues getting opened and ACT discord support requests with users asking why 'X' trigger doesn't show their new 'Y' override text, without understanding that perhaps that trigger doesn't use `Outputs` for Reasons, or whatever.)

**Comment by jacob-keller** [comment]
I think supporting something like this in the user config directory might make sense for some advanced users. I've had some issues in the past with the word choice for specific mechanics, and being able to override in one spot could be useful.

**Comment by Echoring** [comment]
Indeed there are too many unstandard output used now and this can be puzzling to replace general output. Going to close this.
