### ISSUE TITLE
Is there any way to track different phase of boss?

### ISSUE THREAD

**Issue by ChiCheung7** [OverlayPlugin/cactbot#451]
### What's your question?

For example I am encounter UWU and the timeline is wrong starting in the Ifrit phase.
Then I checked the timeline, seems the Ifrit phase was set to 300 second, but we usually kill Garuda in about 150 second.

**Comment by valarnin** [comment]
cactbot timelines separate phases by large time differences if there's any chance of pushing the phase. This is detected with a sync line with a very large window. In UWU:

https://github.com/OverlayPlugin/cactbot/blob/23986d75990c89b247a6ebf9f6d7dc9048f003a6/ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.txt#L53-L61

This line:
```
300.0 "--sync--" StartsUsing { id: "2B5F", source: "Ifrit" } window 300,0
AAAAA BBBBBBBBBB CCCCCCCCCCC { id: "DDDD", source: "EEEEE" } FFFFFFFFFFFF

A = timeline offset/position
B = name. "--sync--" is hidden by default, so this entry isn't visible on the overlay timeline display
C = network line type. StartsUsing corresponds to https://github.com/OverlayPlugin/cactbot/blob/main/docs/LogGuide.md#line-20-0x14-networkstartscasting
D = Ability ID. 2B5F = "Crimson Cyclone", used at the start of Ifrit phase
E = Source actor name
F = Window. "300,0" means "this line can match up to 300 seconds behind, 0 seconds ahead"
```

**Comment by wexxlee** [comment]
> For example I am encounter UWU and the timeline is wrong starting in the Ifrit phase.

I assume you mean cactbot is still showing Garuda entries at the very beginning of Ifrit phase, but as valarnin says, once Garuda starts using Crimson Cyclone, the timeline should re-sync.  If so, that's the expected behavior -- is something different happening for you?

**Comment by xiashtra** [comment]
@ChiCheung7 Was your question suitably answered or do you still have an issue?

**Comment by xiashtra** [comment]
Closing due to lack of response from the original submitter.
