### ISSUE TITLE
oopsy shows missed ??? for every group buff

### ISSUE THREAD

**Issue by Tsunayoshi** [OverlayPlugin/cactbot#467]
I noticed that yesterday in m4s and also today after full pc restart on fate faming -> seems a general problem.
Every group buff like battle voice, shake it off e.g. is shown as "missed ???" as there is a hidden member.
It does not name any party member beside they really out of range:

![image](https://github.com/user-attachments/assets/9b5b2edc-10d5-45ae-957f-62114bdb8ff3)
![image](https://github.com/user-attachments/assets/ec0576c7-1423-48d9-a4c4-bf49e1dbf701)

**Comment by xiashtra** [comment]
Please file using the Bug Report [template](https://github.com/OverlayPlugin/cactbot/issues/new/choose); as it collects additional information needed to investigate.

**Comment by xiashtra** [comment]
Re-opening, additional user report of this issue via Discord.

**Comment by xiashtra** [comment]
We've got a good idea of what's causing this and a fix is pending.
