### ISSUE TITLE
TTS Not Announcing on Linux

### ISSUE THREAD

**Issue by TheOddball** [OverlayPlugin/cactbot#532]
### Description

TTS Not Announcing on Linux

### Additional Details / Steps to Reproduce

Using IINACT as the ACT host, and using the cactbot overlay in an external browser, TTS will still not annouce on Linux, despite it using browser SpeechSynth, and working using this method on Windows.

### Cactbot Module

Raidboss (alerts & timelines)

### Configuration Info

N/A

### Log & Screenshots

This is the output of speechSynthesis.getVoices();
![image](https://github.com/user-attachments/assets/91e66f47-ddd6-48b2-82e2-049a3c8a88a1)

### Confirmation

- [X] I reviewed <a href='/OverlayPlugin/cactbot/blob/main/docs/FAQ-Troubleshooting.md'> Common Issues and Workarounds</a> and verified that my settings are correct.
- [X] I used the search function to confirm this issue doesn't already exist.

**Comment by valarnin** [comment]
If your `OVERLAY_WS` URL uses `127.0.0.1` or `localhost` as the hostname, raidboss treats that as a non-remote connection and does not enable browser TTS.

https://github.com/OverlayPlugin/cactbot/blob/0d662ce39c53e55048c502f75cb5c97c8f8ff6f9/ui/raidboss/raidboss.ts#L24-L31

Try using your internal IP address or hostname as the websocket host instead. If you're not getting the `Click to enable audio` button when you initially load the page, then it's not trying to use the browser for TTS.

**Comment by TheOddball** [comment]
I was using the IINACT Proxy for Cactbot, which *does* show the `Click to enable audio` button. I even force-enabled audio under my browser settings, which did not fix the issue either.

Alas, I have solved this in a different manner, there is a Cactbot fork that uses Google TTS, which solved the issue on my setup. Thank you for the timely response ^^
