### ISSUE TITLE
Cactbot duty timeline shrinks over time

### ISSUE THREAD

**Issue by naroca050** [OverlayPlugin/cactbot#58]
I have a problem in which the timeline for duties in cactbot shrinks over time. I've seen it happen in TEA and now UCoB. At the beginning of the duty, the timeline shows 5-6 lines with 30s of warning in advance as to what is to come as per my configuration but as time goes by it begins shrinking until the number of lines available at the same time becomes just 2.

Leaving the duty and going back in seems to fix the problem until it eventually shrinks again.

I have attached two screenshots below showing the problem: the first one is taken from TEA with 115:35 minutes remaining while the second one was taken with 55:15 minutes left.

![timeline normal](https://github.com/OverlayPlugin/cactbot/assets/158639318/dc26d198-496a-406d-a97b-9daa74f040fd)
![timeline shrunk](https://github.com/OverlayPlugin/cactbot/assets/158639318/2911efec-1982-4073-8fe0-03fe4728bfb5)

Any idea as to why this might be happening?

Thank you in advance.

**Comment by valarnin** [comment]
I have noticed this as well but haven't had time to debug it due to being sick the past ~3 weeks. Does this reproduce with the test timeline in Summerford Farms?

**Comment by naroca050** [comment]
I spent more than an hour in Summerford Farms with the timeline on and it kept going as normal. Then I started a couple of new countdowns for some extra 15 minutes after and it was still fine.

I think it's related to time spent within a duty because of how it resets back to normal after leaving and going back into it.

**Comment by naroca050** [comment]
I did UCoB again today and increased the number of maximum shown lines to 7. The 7th one disappeared after a while and by the end (around 5:48 minutes left in the duty), they had shrunk to 5.

**Comment by Legends0** [comment]
I can confirm this behavior too. I don't know the cause and I know this has been around for a long time (at least a year?).

What I do when this happens is press the Reload overlay button under cactbot's MiniParseOverlay in the OverlayPlugin.dll tab of ACT Plugins and that seems to reset it, until it happens again.

**Comment by wexxlee** [comment]
I can repro this in Summerford Farms, and I've narrowed it down to the (or at least a) set of circumstances that will cause the issue.  If a wipe/reset happens while the top timeline entry being displayed has a duration that extends beyond the timeline event time (e.g., it displays at the top with no remaining time shown), the next time the timeline is started, the maximum number of bars displayed is decremented by 1.  I was able to repeat this behavior until eventually no timeline was shown at all.

Steps:
1.  Summerford Farms: /cd 5
2.  When the first timeline entry ("Angry Dummy") hits zero and continues to then display with no time value, do "/echo end" before it disappears.
3.  Repeat steps as needed.  If you have 6+ bars as your max, you'll either need to progress further in the timeline when the # of bars displayed = max, or repeat multiple times until the number of bars are reduced sufficiently for this to be observable.

There's a comment in `timeline.ts` that might be relevant:  
```typescript
// [...] Durations are extremely awkward as they are manually
// added once their original event has passed.  This means that if you ever jump
// to a new location with an ongoing duration from the past, it will not appear.
```

I'm juggling some IRL stuff, so I may not be able to get back to this until later in the weekend.  If anyone else has time to dive in  and fix it, all yours - but I'd be grateful if you could ping me on Discord so I don't waste time if you're already fixing it. :-)
